=== Keelan-Matthews/calendar-application/RESTful/calendars/validate.xsd
<?xml version="1.0"?>
<!-- Keelan Matthews 21549967 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Restriction on schedule -->
    <xs:element name="schedule">
        <xs:complexType mixed="true">
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="event" type="eventType"/>
            </xs:sequence>
            <xs:attribute name="user" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- Restriction on event -->
    <xs:complexType name="eventType" mixed="true">
        <xs:sequence>
            <xs:element name="title" type="titleType"/>
            <xs:element name="type" type="typeType"/>
            <xs:element name="date" type="dateType"/>
            <xs:element name="guests" type="guestsType"/>
            <xs:element name="venue" type="titleType"/>
            <xs:element name="description" type="descriptionType"/>
        </xs:sequence>
        <xs:attribute name="id" type="idType" use="required"/>
    </xs:complexType>

    <!-- Restriction on event attribute -->
    <xs:simpleType name="idType">
        <xs:restriction base="xs:string">
            <xs:length value="9"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on title -->
    <xs:simpleType name="titleType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="25"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on type -->
    <xs:simpleType name="typeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Event"/>
            <xs:enumeration value="Task"/>
            <xs:enumeration value="Appointment"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on date -->
    <xs:complexType name="dateType" mixed="true">
        <xs:sequence>
            <xs:element name="day" type="dayType" minOccurs="1"/>
            <xs:element name="month" type="monthType" minOccurs="1"/>
            <xs:element name="startingTime" type="startingType" minOccurs="0"/>
            <xs:element name="endingTime" type="startingType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="repeat" type="repeatType" />
    </xs:complexType>

    <!-- Restriction on repeat -->
    <xs:simpleType name="repeatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Daily"/>
            <xs:enumeration value="Weekly"/>
            <xs:enumeration value="Monthly"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on day -->
    <xs:simpleType name="dayType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on month -->
    <xs:simpleType name="monthType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="January"/>
            <xs:enumeration value="February"/>
            <xs:enumeration value="March"/>
            <xs:enumeration value="April"/>
            <xs:enumeration value="May"/>
            <xs:enumeration value="June"/>
            <xs:enumeration value="July"/>
            <xs:enumeration value="August"/>
            <xs:enumeration value="September"/>
            <xs:enumeration value="October"/>
            <xs:enumeration value="November"/>
            <xs:enumeration value="December"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Starting time restriction -->
    <xs:simpleType name="startingType">
        <xs:restriction base="xs:token">
            <xs:pattern value="([0-9]{2}:[0-9]{2} )(AM|PM)"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on guests type -->
    <xs:complexType name="guestsType">
        <xs:sequence minOccurs="0" maxOccurs="10">
            <xs:element name="guest" type="guestType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Restriction on guest type -->
    <xs:complexType name="guestType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="email" type="nameType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Restriction on name -->
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction on description -->
    <xs:simpleType name="descriptionType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Keelan-Matthews/calendar-application/src/RESTful/calendars/sample_data.xml
<?xml version="1.0"?>
<schedule user="DaddyLongLegs"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	      xsi:noNamespaceSchemaLocation="validate.xsd">
	<event id="IMY210101">
		<title>IMY 210 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">	
			<day>2</day>
			<month>March</month>
			<startingTime>03:30 PM</startingTime>
			<endingTime>04:30 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Yan</name>
				<email>yan.wong@up.ac.za</email>
			</guest>
			<guest>
				<name>Daddy</name>
				<email>daddylonglegs@gmail.com</email>
			</guest>
		</guests>
		<venue>IT building</venue>
		<description>
			World worst brain surgeon giving class on XML.
		</description>
	</event>
</schedule>

=== Keelan-Matthews/calendar-application/RESTful/calendars/bob.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schedule user="peter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
	<event id="CRAZYEGX4">
		<title>Crazy Event</title>
		<type>Event</type>
		<date repeat="Monthly">
			<day>14</day>
			<month>May</month>
			<startingTime>01:08 AM</startingTime>
			<endingTime>05:57 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelanmatthews123@gmail.com</email>
			</guest>
		</guests>
		<venue>Crazy Place</venue>
		<description>This is a crazy event</description>
	</event>
	<event id="CRYSETISY">
		<title>Cry sesh</title>
		<type>Task</type>
		<date repeat="Weekly">
			<day>27</day>
			<month>May</month>
			<startingTime>08:15 AM</startingTime>
			<endingTime>09:15 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
		</guests>
		<venue>Caylees room</venue>
		<description>Shame he needs it</description>
	</event>
</schedule>

=== Keelan-Matthews/calendar-application/RESTful/calendars/yan.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="stylesheet.xsl"?>
<schedule user="peter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
	<event id="CRAZYEGX4">
		<title>Crazy Event</title>
		<type>Event</type>
		<date repeat="Monthly">
			<day>1</day>
			<month>May</month>
			<startingTime>09:08 AM</startingTime>
			<endingTime>05:57 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelanmatthews123@gmail.com</email>
			</guest>
		</guests>
		<venue>Crazy Place</venue>
		<description>This is a crazy event</description>
	</event>
	<event id="CRYSETISY">
		<title>Cry sesh</title>
		<type>Task</type>
		<date repeat="Weekly">
			<day>2</day>
			<month>February</month>
			<startingTime>08:15 AM</startingTime>
			<endingTime>09:15 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
		</guests>
		<venue>Caylees room</venue>
		<description>Shame he needs it</description>
	</event>
	<event id="IMY2102SS">
		<title>IMY 210 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">
			<day>24</day>
			<month>February</month>
			<startingTime>10:15 AM</startingTime>
			<endingTime>11:15 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>Centenary</venue>
		<description>XML and stuff is hard</description>
	</event>
	<event id="COS211092">
		<title>COS 216 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">
			<day>24</day>
			<month>February</month>
			<startingTime>07:00 AM</startingTime>
			<endingTime>08:00 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
			<guest>
				<name>Carl</name>
				<email>carl@icloud.com</email>
			</guest>
		</guests>
		<venue>IT Building</venue>
		<description>Boop boop beep boop 010010010011100100101</description>
	</event>
	<event id="PLAYL10SK">
		<title>Play LoL</title>
		<type>Task</type>
		<date repeat="Monthly">
			<day>7</day>
			<month>January</month>
			<startingTime>07:00 AM</startingTime>
			<endingTime>11:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>Home</venue>
		<description>I am the best player out there</description>
	</event>
	<event id="DONOTJW81">
		<title>Do nothing</title>
		<type>Event</type>
		<date>
			<day>10</day>
			<month>May</month>
			<startingTime>07:00 AM</startingTime>
			<endingTime>07:00 PM</endingTime>
		</date>
		<guests>
		</guests>
		<venue>The beach</venue>
		<description>Just kidding imagine having any free time nowadays</description>
	</event>
	<event id="COS21DS21">
		<title>COS 212 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">
			<day>1</day>
			<month>April</month>
			<startingTime>06:00 PM</startingTime>
			<endingTime>11:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>IT</venue>
		<description>Default description because I'm lazy</description>
	</event>
	<event id="GYMSTFD11">
		<title>Gym Stuff</title>
		<type>Event</type>
		<date repeat="Monthly">
			<day>8</day>
			<month>March</month>
			<startingTime>08:00 PM</startingTime>
			<endingTime>09:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>Virgin Active</venue>
		<description>Default description because I'm lazy</description>
	</event>
	<event id="SEEFR0123">
		<title>See friend</title>
		<type>Event</type>
		<date>
			<day>8</day>
			<month>June</month>
			<startingTime>04:00 PM</startingTime>
			<endingTime>05:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>Friend's House</venue>
		<description>Default description because I'm lazy</description>
	</event>
</schedule>

=== Keelan-Matthews/calendar-application/RESTful/calendars/peter.xml
<?xml version="1.0"?>
<schedule user="peter"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	      xsi:noNamespaceSchemaLocation="validate.xsd">
	<event id="IMY210E13">
		<title>IMY 210 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">	
			<day>2</day>
			<month>March</month>
			<startingTime>03:30 PM</startingTime>
			<endingTime>04:30 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Yan</name>
				<email>yan.wong@up.ac.za</email>
			</guest>
			<guest>
				<name>Daddy</name>
				<email>daddylonglegs@gmail.com</email>
			</guest>
		</guests>
		<venue>IT building</venue>
		<description>
			World worst brain surgeon giving class on XML.
		</description>
	</event>
    <event id="IMY211E64">
		<title>IMY 211 Classes</title>
		<type>Event</type>
		<date repeat="Monthly">	
			<day>4</day>
			<month>January</month>
			<startingTime>05:30 PM</startingTime>
			<endingTime>06:30 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Yan</name>
				<email>yan.wong@up.ac.za</email>
			</guest>
			<guest>
				<name>Daddy</name>
				<email>daddylonglegs@gmail.com</email>
			</guest>
		</guests>
		<venue>Centenary</venue>
		<description>
			Crazy 3D stuff.
		</description>
	</event>
	<event id="IMY211E90">
		<title>Gym</title>
		<type>Event</type>
		<date repeat="Monthly">	
			<day>8</day>
			<month>January</month>
			<startingTime>05:30 PM</startingTime>
			<endingTime>06:30 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Yan</name>
				<email>yan.wong@up.ac.za</email>
			</guest>
			<guest>
				<name>Daddy</name>
				<email>daddylonglegs@gmail.com</email>
			</guest>
		</guests>
		<venue>Virgin Active</venue>
		<description>
			Time to go gym at Virgin Active and get massive gains
		</description>
	</event>
</schedule>

=== Keelan-Matthews/calendar-application/RESTful/calendars/keelan.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="stylesheet.xsl"?>
<schedule user="peter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validate.xsd">
	<event id="CRAZYEGX4">
		<title>Crazy Event</title>
		<type>Event</type>
		<date repeat="Monthly">
			<day>14</day>
			<month>May</month>
			<startingTime>09:08 AM</startingTime>
			<endingTime>05:57 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelanmatthews123@gmail.com</email>
			</guest>
		</guests>
		<venue>Crazy Place</venue>
		<description>This is a crazy event</description>
	</event>
	<event id="CRYSETISY">
		<title>Cry sesh</title>
		<type>Task</type>
		<date repeat="Weekly">
			<day>27</day>
			<month>February</month>
			<startingTime>08:15 AM</startingTime>
			<endingTime>09:15 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
		</guests>
		<venue>Caylees room</venue>
		<description>Shame he needs it</description>
	</event>
	<event id="IMY2102SS">
		<title>IMY 210 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">
			<day>20</day>
			<month>February</month>
			<startingTime>10:15 AM</startingTime>
			<endingTime>11:15 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>Centenary</venue>
		<description>XML and stuff is hard</description>
	</event>
	<event id="COS211092">
		<title>COS 216 Classes</title>
		<type>Event</type>
		<date repeat="Weekly">
			<day>24</day>
			<month>February</month>
			<startingTime>07:00 AM</startingTime>
			<endingTime>08:00 AM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Cayleeeee</name>
				<email>Cayleeeeiscool@icloud.com</email>
			</guest>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
			<guest>
				<name>Carl</name>
				<email>carl@icloud.com</email>
			</guest>
		</guests>
		<venue>IT Building</venue>
		<description>Boop boop beep boop 0100100100100100101</description>
	</event>
	<event id="PLAYL10SK">
		<title>Play LoL</title>
		<type>Task</type>
		<date repeat="Monthly">
			<day>1</day>
			<month>January</month>
			<startingTime>07:00 AM</startingTime>
			<endingTime>11:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Keelan</name>
				<email>keelan@icloud.com</email>
			</guest>
		</guests>
		<venue>Home</venue>
		<description>I am the best player out there</description>
	</event>
	<event id="JLOOPEEAE">
		<title>J Loops</title>
		<type>Event</type>
		<date>
			<day>5</day>
			<month>June</month>
			<startingTime>10:00 AM</startingTime>
			<endingTime>08:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Caylee</name>
				<email>Badbitch@gmail.com</email>
			</guest>
		</guests>
		<venue>Loftus </venue>
		<description>Vibessssss</description>
	</event>
	<event id="TRYMAT0MA">
		<title>Try make friends</title>
		<type>Task</type>
		<date repeat="Daily">
			<day>26</day>
			<month>May</month>
			<startingTime>01:00 PM</startingTime>
			<endingTime>06:00 PM</endingTime>
		</date>
		<guests>
			<guest>
				<name>Nobody</name>
				<email>Nobody@nowhere.gone</email>
			</guest>
		</guests>
		<venue>Anywhere that lets me in</venue>
		<description>I am lonely...</description>
	</event>
</schedule>
